---
- project:
    check:
      jobs:
        - openstack-tox-linters
    gate:
      jobs:
        - openstack-tox-linters
    post:
      jobs:
        - stx-compile-upload-git-mirror

- job:
    name: stx-compile-upload-git-mirror
    parent: upload-git-mirror
    description: Mirrors opendev.org/starlingx/compile to github.com/starlingx/compile
    vars:
      git_mirror_repository: starlingx/compile
    secrets:
      - name: git_mirror_credentials
        secret: stx-compile-github-secret3
        pass-to-parent: true

- secret:
    name: stx-compile-github-secret3
    data:
      user: git
      host: github.com
      # yamllint disable-line rule:line-length
      host_key: github.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCj7ndNxQowgcQnjshcLrqPEiiphnt+VTTvDP6mHBL9j1aNUkY4Ue1gvwnGLVlOhGeYrnZaMgRK6+PKCUXaDbC7qtbW8gIkhL7aGCsOr/C56SJMy/BCZfxd1nWzAOxSDPgVsmerOBYfNqltV9/hWCqBywINIR+5dIg6JTJ72pcEpEjcYgXkE2YEFXV1JHnsKgbLWNlhScqb2UmyRkQyytRLtL+38TGxkxCflmO+5Z8CSSNY7GidjMIZ7Q4zMjA2n1nGrlTDkzwDCsw+wqFPGQA179cnfGWOWRVruj16z6XyvxvjJwbz0wQZ75XK5tKSb7FNyeIEs4TT4jk+S4dhPeAUC5y+bDYirYgM4GC7uEnztnZyaVWQ7B381AK4Qdrwt51ZqExKbQpTUNn+EjqoTwvqNj4kqx5QUCI0ThS/YkOxJCXmPUWZbhjpCg56i+2aB6CmK2JGhn57K5mj0MNdBXA4/WnwH6XoPWJzK5Nyu2zB3nAZp+S5hpQs+p1vN1/wsjk=
      ssh_key: !encrypted/pkcs1-oaep
        - L9m/uYiBuVke4/Qw2gWS2fbMf8jz2gCgO6ppoqmBt1lrm6gptnjT4k/+i2kAEWFKT0/tz
          VrLEg6JJpYjOR5vZwLxT24xeCTPlRwXG1SSf/StRDWjc/GmVJ1ctNMeHrBQ3y2KVdYiAw
          yXOKW6G3MKY6ezB8SLLC0HP+6WirkjGDXR3Fm7avadyfMHAb8ZIXpqK/ESrEkmC73bum1
          Kxisg8pew0fLHbJfUf7K5ZYtds/IasHE3GtkbVjv2/gP/GXtPgM8Ap5/Zox4mcUlHIuq1
          pkQn4Rj75hcq0QFC+Wq4yBiDUnuWIqJF7ond56IHPbJwbue9ny2vm9J7cd8Flf0JZrMtp
          GhKKTLhWra2Q8nmDNtpy1UFvddTknN4sNh+nENiGWz+z1DMD6X4uzeRhJ31r5CSw1E1Pb
          ayY0+Jh0EI4a6yKUFRbB1BV4dUGN7nafjTDyq1Wr+Z/r9lMYPPesXiCgqlaQpCZ2IW5IM
          XLJjQgqlhN78zwYEzafm4AAMqEEzIAPiZ4netg6HHix+T5Gb4GwXANxbPl2rmt18P/L8g
          81axekiDnioLc+7IP267LHUmi2iVMcfzG6nkQ8ru96MGWJnu4dtTiPLT7CwLxnZnDsozt
          jKbNC7ZYu6CaRMa4R+zjLElEKL+VOCK8yzvRyxs/pSpYAh8vLQ4IEC4MHDlNYc=
        - ZWUF3ygZFFFzky3z0ZuLsxGjdwOf079d/ZWGBH7wpPs2C/wnUxY1j5390alP7ABs/EIqO
          6EPVAvBL/PciKth21PvlzL+3awKudOxVPuc151cQc43sUlOAvnGPmzFXzPDYu6r+8kO2m
          n9ApFwrfKa6d9hdKwXJRTr+DYJoOZnOEYD0fKrrkKRN2BANmMXDicobAxi6Dm1kV0AlOj
          eKZuSrnM1QA4p8UiSbd8mHC6iENH0eLKiB9YzGnhyFkFjK2sASZjHLkYEVkr8d+dtY/+3
          8n2KWLHNhArEV+VOPszHppMo/8gEISG1/zOGKM7MjVDv2BmlU1CajWAz/BoOaskw2NqUi
          zg9FgoX8zf9eQVg3I6QPPjxJIe56sbmBTpWnapZoQhfJpiSmxaP12DkqQv5KgZ8TtmMGh
          +I41YHTIEWb6WNnMPx+JQfBM0ndyuQO3vsYFNddTzqwM1fu2uGwr6GGzLp//WVfeUx1cr
          K4i6Z67sp+FNiMGm9yC7cYq1/ojd2tfebwXy7kFRWDygFccnUXANWIkH8+ON2Lx2DHH4V
          55rHq/rro4DlN+jdz5ldxySv/XqL4hny0/mrTGGUSRiOnG6eJsh54bPG9XO7zqcAZum0l
          plxHdT5Rft0fkCYPHpGPQIAUhfx7SCoF+5B0Pliat3SK9878UmOyAiQA1DpEhc=
        - kPBNl1S1IRRgayzQ9M6x/eWsh39xw2wLT4+WBNOqhOuvug3omNyqUjOnqQUjJM5nJZ4FE
          rFE1zZaymkaE84OgUIzgvVrLyfKxXKSnYcI7BMC9Gk1GU5UNLwYrTk5IRt03fO/gqEUdT
          qBXv6/VZhASyjY1cmmasR2ux5RcqBgpAtjOqI1cCVH2ceSLy00prXL8LNwcPwtBQU8LPy
          kO6bnFVduEvcUlWSpRO2yiSgy0ftmNTzyZaU8KmkNyRqP8ilUjpUmSmBMCT580ia8JBaS
          Flfn/0YzXsjh2C0NnomFfOJ5vo7dqqH28J6X25ULDkVsljS6ydyl1J1fNO6yTlJx1wLv6
          s6CDs13LpS99YZ9dc9jnLrTjcCTtCenXE4RRRCTVWkE/in+ZjmmXeieHrbQtdZl55/Zid
          JcJK6i0gapeOZ9GhwCN9ZsjPlGtShNLX+b7AffwbVKgcvcwPpItERt+2yNp7UJNnBFZK8
          IRVmicluJxYb3oHoUBpFCpjQkClo8cNQlPhNUYh1sJ+d321ruZW4QXmW2e5uB1oByu2Bg
          40NMesNN1U3e8C1CLdy2LQkdw7vmYTVkJ68iqZAWm0leFKN017a6SEQyQgXoAf+6XrCPZ
          0VqprHOUt4rf7g1MM06VhweKcyYJKbNuUvVz1Xt0eVxmbwbFmbZdaCP1iaHS3k=
        - T914K2IOAYZAWkg6QERAnfMxxCrmYUUH92lj+CfpxFQM8R1jqdSwggzFrFebB3Ipa2bpI
          zVXVIfDZ9BFFx/Z0mtmA0vnBXz0YgH/8RK5sVLhNtFGpwf2AnKUPypNJEII05SiR3gTiD
          iFIw8VaKgQsN/Jfb6tcpjUjmVjY7Pt5kNqSV/9stkw+ywF/C4dAjkgukKL/2hD3NLqV6g
          VCZXG23283dSlWoj9i+ZqboG52eJub1L3n2FtjW+Naoajg0b2GDudxqGEh2qNaSRqLkEa
          owRYoq3pXBwUO5SkeFgC8oQAkGLrOgbHkbZizSdsWExo5XDxYvwpg7sfgr7wkNoxfn2nd
          bEkmbYEP2hIlX3pEddS9f+8+wt8ROIQn156mLQkAE79sFKGozIikJbqnDYLE/oSby/kxr
          gsTG/bp+/2+7ATxanhXPAr+d4JSzUkBI1FF/cSPBaNAUGRl7/fXUdbODqaFk0xXq6abgf
          xDrUaxv8c7C0SkrmMLcnmBJT9+gnyHcW2QbNONSXoUr7FwQ02sXI5xPpWGc2Zfg9VRhpa
          D4/UupRB7VLSUDXoNb1bq/uIB5GA1K/wnJtIUgM4z08Fb3YgnZgD8vKWSXd6uhTd4IypH
          HsbzvvDLtpna4hJ/zm0zbBXiO1+Kg7On9PiYZwLYX7Cp0SLf1MmclTDApd300w=
        - gS8xupoYDouqt94lL/GaDQRrkEA/XXfcrV2ms7RgV/5X7fw0Rq7P8PIUOBRloKiA/OHY+
          IvtfOxqiE5d3xWFzhXcWrODVJSCXLwAvQXl9UcPNshUoWAsHUmxJY0zSkfp9hT8V0f8yr
          UFs29aNO6f5RVkytTAKmdDryM2QBS4m1vLF8HlZybEmeWzltQJ70ww5UwVkFZ/PBrfots
          gYN5FG/IZUyhRgTreSaIHAduNWrfEJ2W1XcHkOkPCObZkyBvUoTkrFoziFjneQVPZHoRI
          xWxxiu5nuqsAafqa3XgGkSPSXpIaxEQy01Lo9NgSZWBg0obc8+GAWUVeGJ7bYiB4uA40y
          uZHfV+6xE5o1ebgK6fCM6GCVUK7pTZ8xRKDbjq1b8Zqwlay5cwjpl4YiYTUH39x5KlPQ3
          1mYS/gb1v7KTVmPrEPJdNi3I0d8TOpdOnKkjK25dlE8c1Zwox5yBy6gKlWUb/9G+lVh8e
          CSU94KwqukJOAi4WHEcWlRvUAmJhKMakXVrd3qyKjNw7YyM3t/h4mv/LL9UyFuIKfkGo0
          xcQ77ECDEucL7O/ngvCeNrcjONgC/bCYHGm/Hd1oJKXBRYL+iL/XSzkB6Kt3jF2roObrA
          TtYIv0nY2U2uu+huvp5kzA9TWiE5cVj4hEMqGXscHBvpu9e0vSWSbBADqDcgyM=
        - r/LvyMyHrMdINOZoxV3yFpckXiyR8YS5NS4z0nZyefrzAYRhcSNUm5fbFIUTlgACF3H0B
          xUO7wXu1tZBUgLupRCyy0EqAIvqjsdUAr6xtbpTNXUpeRoTiqug9FSZgw90vDsvfWiR6u
          38IBlDON9s0bySLsTDQtyf7edhxInTeO5Migstm4dHIzu1xr8nA+tB0yrfsF7HVxJ9O3U
          OVYYqIzFwZVRUXLyjMSjGBVcmRwv2xh24SvpqwGuqxIBna64A2ZTvjzdyNe2oGPS34KFJ
          fwMMfymm3bPi4ZbE7lVWM2dbduFsB6fpXyXMibO1y7lhskF9M+aX7N1kdFjekGNmGi2ZB
          94hunx6EkBC975Yh7dABVoZ8EQo2gdNiFc+z/8PUmmLc7WsXvXkKgw+pDU+GYAht/3umA
          LQ42NoTvmQcKnP0iwbJP+WAnQh+tFYFaa8mBMfB+LgBr+JpZs1JeAMxkKuTp2N1wFJ6w1
          U98qeE5EijwfwQws9kXiv4Jv9+AP9j34AXMBiElb9NUtTRLlbMsADsV4GTUwpm8nBxtTZ
          cdvz9yTJg9976i+CG7ujAJoP5e5Oyw9o4TyOlgrvMRv8S+zhQwvQQxnPWYxiZtojGKukQ
          GYu9ztw+9RpLUFIb4z7tmA0L+QXwwFqGtkvOrilxDZnoC/z7/3OIuLYYkDO9o0=
        - jRIEE16mMfAk7Tai05kWM1qryLtesg4bGV89fRv19iqjSwxO4Wakmg0ICy5mWK5518aiy
          0QcyF9pX4sO6lTWhhcmZGXY1X9hLqazcoulNKBhRifmzFYCfQiy7XVnp+/Ta6C1Mu0tom
          FFet5OVbZsPR1s4Nh8/xideR7YbblzN7SNZJg3IEjLsdvpDr7XonzenVSd2ThhHBfiTvf
          hYuPIiIQicJo9K7suBVREZ2FX1zv5MhepD8mG8AZpNP9bjQYdHU/Mg7SZTPfc8Dnft40G
          BEatL7kRKhZOtOUBJdT3xAoj8/ym7C4WV2YxEZ9Wc/P3tTYl2p7Iq7shTSAlBZa706iLY
          qWkdFbcEu82ypO5VCdjfBHJV0hwgAI9ZwImaJg8Mi8hXkldeDcqTMMIM4NaNgLiw2FEnn
          4q9aUiZZkFabqxvJMTofLGb+JPakBJNPcdgBKvcdDJsa+pCcaY25RfCY+7uMAdP25YZsu
          QICnvbV4kbNt6Xz6yjP25G/R4p5BtlLXamaY0DWGhKoktYWiQ1HWHRcWzsGChQkofIxE2
          lrvYuA5YV79a1CE/GE6OiVm3XyRntcy0dZkcFfwINfDD7eBvjlFEicSeCSrtkSe3VRk5v
          Xfge1y1MVyLa3co7fK9GM7IQkgpUZxGsfAwfHhQNiXtfxUUlN5Lah1zSiHKr2Y=
